version: '3.9'

services:

  db:
    image: postgres:16

    container_name: healthcare_db

    restart: always

    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: healthcare_backend

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DB_NAME: healthcare_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: