# Generated by Django 5.2.14 on 2026-06-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_ejecucion', models.FloatField(blank=True, null=True)),
                ('registros_extraidos', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('registros_nulos', models.IntegerField(default=0)),
                ('registros_fuera_rango', models.IntegerField(default=0)),
                ('registros_cargados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('en_proceso', 'En proceso')], default='en_proceso', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('archivo_fuente', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log ETL',
                'verbose_name_plural': 'Logs ETL',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
