# Generated by Django 6.0.5 on 2026-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('systolic_pressure', models.IntegerField()),
                ('diastolic_pressure', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('glucose', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('temperature', models.FloatField()),
                ('family_history', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_consumption', models.BooleanField(default=False)),
                ('physical_activity', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('preliminary_diagnosis', models.CharField(max_length=255)),
                ('disease_risk', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=20)),
                ('consultation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
