# Generated by Django 5.2.14 on 2026-06-06 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField()),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_train', models.IntegerField(default=0)),
                ('registros_test', models.IntegerField(default=0)),
                ('modelo', models.CharField(default='RandomForestClassifier', max_length=100)),
                ('features', models.JSONField(default=list)),
                ('importancia', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_entrenamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métricas ML',
                'verbose_name_plural': 'Métricas ML',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
